### ISSUE TITLE
NotImplementedError: Only 3D, 4D, 5D padding with non-constant padding are supported for now

### ISSUE THREAD

**Issue by hujinsen** [NVlabs/FUNIT#17]
```text
Traceback (most recent call last):
  File "/home/hu/disk1/EXP_Part2/FUNIT/train.py", line 112, in <module>
    train()
  File "/home/hu/disk1/EXP_Part2/FUNIT/train.py", line 91, in train
    d_acc = trainer.dis_update(mc, mc, config)
  File "/home/hu/disk1/EXP_Part2/FUNIT/trainer.py", line 65, in dis_update
    al, lfa, lre, reg, acc = self.model(co_data, cl_data, hp, 'dis_update')
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hu/disk1/EXP_Part2/FUNIT/funit_model.py", line 53, in forward
    l_real_pre, acc_r, resp_r = self.dis.calc_dis_real_loss(xb, lb)
  File "/home/hu/disk1/EXP_Part2/FUNIT/networks.py", line 81, in calc_dis_real_loss
    resp_real, gan_feat = self.forward(input_real, input_label)
  File "/home/hu/disk1/EXP_Part2/FUNIT/networks.py", line 65, in forward
    feat = self.cnn_f(x)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hu/disk1/EXP_Part2/FUNIT/blocks.py", line 163, in forward
    x = self.conv(self.pad(x))
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/modules/padding.py", line 171, in forward
    return F.pad(input, self.padding, 'reflect')
  File "/home/hu/anaconda3/envs/hhh/lib/python3.7/site-packages/torch/nn/functional.py", line 2840, in pad
    raise NotImplementedError("Only 3D, 4D, 5D padding with non-constant padding are supported for now")
NotImplementedError: Only 3D, 4D, 5D padding with non-constant padding are supported for now
```
any ideas?  thanks!

**Comment by biubiu111** [comment]
你好，请问你是如何处理这个bug的？它是由什么原因引起的呢？谢谢
